### ISSUE TITLE
Nordnet from the terminal

### ISSUE THREAD

**Issue by jaimejim** [nordnet/ui#253]
I would like to know if someone has perhaps implemented a terminal interface to the Nordnet account. I'd like to be able to see the stock status screen, buy/sell and do a bit of scripting on my own, but I do not know if there are any open APIs at all. 

To be more specific, something like https://alpaca.markets/
To perform operations in a similar fashion as https://medium.com/automation-generation/buying-and-selling-stocks-from-the-command-line-5b4dd5628078

**Comment by shmidt-i** [comment]
Hey @jaimejim, thanks for the interest!

I think https://github.com/nordnet/next-api-v2-examples is close to what you are looking for. This library is the GUI part for the Nordnet web application.
