### ISSUE TITLE
hideLabel prop on Input.Text hides entire element

### ISSUE THREAD

**Issue by eliasnorrby** [nordnet/ui#318]
Passing the `hideLabel` prop to `Input.Text` hides not only the label but the entire input field. 

`Input.Text` on [storybook](https://nordnet.github.io/ui/?path=/story/molecules-input-text--hidden-label)

`git bisect` between `v1.45.0` and `v1.47.0` says the first bad commit was edabc83e1146cd

**Comment by shmidt-i** [comment]
Hey, nice catch!

We will take a look tomorrow!
