### ISSUE TITLE
Expose some types

### ISSUE THREAD

**Issue by LifeofMichal** [nordnet/ui#899]
Certain pages are importing types from Nordnet/UI by actual folder bath. It is an anti-pattern we possibly should not follow, so we're currently in process of exposing all the types used by webapp-next.

![Screenshot 2021-05-05 at 16 33 23](https://user-images.githubusercontent.com/15144524/117158427-b3183900-adbf-11eb-93fa-90b03f4f3740.png)

There are two relevant branches to the issue, one here, and the other on webapp-next:
- Nordnet/UI: [fix/expose-some-types](https://github.com/nordnet/ui/tree/fix/expose-some-types)
- Webapp-next: [fix/exposing-types-from-nordnet-ui](https://scm.prod.nordnet.se/projects/SHELL/repos/webapp-next/compare/diff?sourceBranch=refs%2Fheads%2Ffix%2Fexposing-types-from-nordnet-ui&targetRepoId=1044)

The branches are being updated in parallel, expose type in UI, update imports in webapp-next, if you're curious to check it out, yalc publish nordnet/ui, add it to webapp-next, and go crazy!

Allegedly that has been on a backburner for some type, so might as well do it now.

**Comment by victoriatomzik** [comment]
@LifeofMichal ready to close?

**Comment by LifeofMichal** [comment]
@victoriatomzik Ah, completely forgot, yes, can be closed :D
